name: n_gamepad_example
description: Demonstrates how to use the n_gamepad plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  n_gamepad:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
