name: n_gamepad
description: "Flutter plugin for listening to various game controller inputs."
repository: https://github.com/devEnju/n_gamepad
issue_tracker: https://github.com/devEnju/n_gamepad/issues
version: 0.0.4
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.marvinvogl.n_gamepad
        pluginClass: GamepadPlugin
