name: n_gamepad
description: Flutter plugin for listening to various game controller inputs.
repository: https://github.com/devEnju/n_gamepad
issue_tracker: https://github.com/devEnju/n_gamepad/issues
version: 0.0.2
homepage:

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.marvinvogl.n_gamepad
        pluginClass: GamepadPlugin
