// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.marvinvogl.n_gamepad.GamepadChannel`
extension type GamepadChannel._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/marvinvogl/n_gamepad/GamepadChannel',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<GamepadChannel> type = $GamepadChannel$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory GamepadChannel() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<GamepadChannel>();
  }

  static final _id_assignKeyCallable = _class.staticMethodId(
    r'assignKeyCallable',
    r'(Lcom/marvinvogl/n_gamepad/KeyCallable;)Lcom/marvinvogl/n_gamepad/KeyCallable;',
  );

  static final _assignKeyCallable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.marvinvogl.n_gamepad.KeyCallable assignKeyCallable(com.marvinvogl.n_gamepad.KeyCallable callable)`
  /// The returned object must be released after use, by calling the [release] method.
  static KeyCallable? assignKeyCallable(KeyCallable? callable) {
    final _$callable = callable?.reference ?? jni$_.jNullReference;
    return _assignKeyCallable(
      _class.reference.pointer,
      _id_assignKeyCallable.pointer,
      _$callable.pointer,
    ).object<KeyCallable?>();
  }

  static final _id_assignMotionCallable = _class.staticMethodId(
    r'assignMotionCallable',
    r'(Lcom/marvinvogl/n_gamepad/MotionCallable;)Lcom/marvinvogl/n_gamepad/MotionCallable;',
  );

  static final _assignMotionCallable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.marvinvogl.n_gamepad.MotionCallable assignMotionCallable(com.marvinvogl.n_gamepad.MotionCallable callable)`
  /// The returned object must be released after use, by calling the [release] method.
  static MotionCallable? assignMotionCallable(MotionCallable? callable) {
    final _$callable = callable?.reference ?? jni$_.jNullReference;
    return _assignMotionCallable(
      _class.reference.pointer,
      _id_assignMotionCallable.pointer,
      _$callable.pointer,
    ).object<MotionCallable?>();
  }

  static final _id_clearListener = _class.staticMethodId(
    r'clearListener',
    r'()V',
  );

  static final _clearListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void clearListener()`
  static void clearListener() {
    _clearListener(_class.reference.pointer, _id_clearListener.pointer).check();
  }
}

final class $GamepadChannel$Type$ extends jni$_.JType<GamepadChannel> {
  @jni$_.internal
  const $GamepadChannel$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/marvinvogl/n_gamepad/GamepadChannel;';
}

/// from: `com.marvinvogl.n_gamepad.KeyCallable`
extension type KeyCallable._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/marvinvogl/n_gamepad/KeyCallable',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<KeyCallable> type = $KeyCallable$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $KeyCallable> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'callback(III)V') {
        _$impls[$p]!.callback(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![2] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(jni$_.JImplementer implementer, $KeyCallable $impl) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.marvinvogl.n_gamepad.KeyCallable',
      $p,
      _$invokePointer,
      [if ($impl.callback$async) r'callback(III)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory KeyCallable.implement($KeyCallable $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<KeyCallable>();
  }
}

extension KeyCallable$$Methods on KeyCallable {
  static final _id_callback = KeyCallable._class.instanceMethodId(
    r'callback',
    r'(III)V',
  );

  static final _callback =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void callback(int id, int keyCode, int action)`
  void callback(core$_.int id, core$_.int keyCode, core$_.int action) {
    _callback(
      reference.pointer,
      _id_callback.pointer,
      id,
      keyCode,
      action,
    ).check();
  }
}

abstract base mixin class $KeyCallable {
  factory $KeyCallable({
    required void Function(core$_.int id, core$_.int keyCode, core$_.int action)
    callback,
    core$_.bool callback$async,
  }) = _$KeyCallable;

  void callback(core$_.int id, core$_.int keyCode, core$_.int action);
  core$_.bool get callback$async => false;
}

final class _$KeyCallable with $KeyCallable {
  _$KeyCallable({
    required this._callback,
    this.callback$async = false,
  });

  final void Function(core$_.int id, core$_.int keyCode, core$_.int action)
  _callback;
  final core$_.bool callback$async;

  void callback(core$_.int id, core$_.int keyCode, core$_.int action) {
    return _callback(id, keyCode, action);
  }
}

final class $KeyCallable$Type$ extends jni$_.JType<KeyCallable> {
  @jni$_.internal
  const $KeyCallable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/marvinvogl/n_gamepad/KeyCallable;';
}

/// from: `com.marvinvogl.n_gamepad.MotionCallable`
extension type MotionCallable._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/marvinvogl/n_gamepad/MotionCallable',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MotionCallable> type = $MotionCallable$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $MotionCallable> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'callback(II)V') {
        _$impls[$p]!.callback(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $MotionCallable $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.marvinvogl.n_gamepad.MotionCallable',
      $p,
      _$invokePointer,
      [if ($impl.callback$async) r'callback(II)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory MotionCallable.implement($MotionCallable $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<MotionCallable>();
  }
}

extension MotionCallable$$Methods on MotionCallable {
  static final _id_callback = MotionCallable._class.instanceMethodId(
    r'callback',
    r'(II)V',
  );

  static final _callback =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void callback(int keyCode, int action)`
  void callback(core$_.int keyCode, core$_.int action) {
    _callback(reference.pointer, _id_callback.pointer, keyCode, action).check();
  }
}

abstract base mixin class $MotionCallable {
  factory $MotionCallable({
    required void Function(core$_.int keyCode, core$_.int action) callback,
    core$_.bool callback$async,
  }) = _$MotionCallable;

  void callback(core$_.int keyCode, core$_.int action);
  core$_.bool get callback$async => false;
}

final class _$MotionCallable with $MotionCallable {
  _$MotionCallable({
    required this._callback,
    this.callback$async = false,
  });

  final void Function(core$_.int keyCode, core$_.int action) _callback;
  final core$_.bool callback$async;

  void callback(core$_.int keyCode, core$_.int action) {
    return _callback(keyCode, action);
  }
}

final class $MotionCallable$Type$ extends jni$_.JType<MotionCallable> {
  @jni$_.internal
  const $MotionCallable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/marvinvogl/n_gamepad/MotionCallable;';
}
