// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.marvinvogl.n_gamepad.GamepadChannel`
extension type GamepadChannel._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/marvinvogl/n_gamepad/GamepadChannel',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<GamepadChannel> type = $GamepadChannel$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory GamepadChannel() {
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
    ).object<GamepadChannel>();
  }

  static final _id_assignKeyCallback = _class.staticMethodId(
    r'assignKeyCallback',
    r'(Lcom/marvinvogl/n_gamepad/KeyCallback;)Lcom/marvinvogl/n_gamepad/KeyCallback;',
  );

  static final _assignKeyCallback =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.marvinvogl.n_gamepad.KeyCallback assignKeyCallback(com.marvinvogl.n_gamepad.KeyCallback callback)`
  /// The returned object must be released after use, by calling the [release] method.
  static KeyCallback? assignKeyCallback(KeyCallback? callback) {
    final _$callback = callback?.reference ?? jni$_.jNullReference;
    return _assignKeyCallback(
      _class.reference.pointer,
      _id_assignKeyCallback.pointer,
      _$callback.pointer,
    ).object<KeyCallback?>();
  }

  static final _id_assignMotionCallback = _class.staticMethodId(
    r'assignMotionCallback',
    r'(Lcom/marvinvogl/n_gamepad/MotionCallback;)Lcom/marvinvogl/n_gamepad/MotionCallback;',
  );

  static final _assignMotionCallback =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public com.marvinvogl.n_gamepad.MotionCallback assignMotionCallback(com.marvinvogl.n_gamepad.MotionCallback callback)`
  /// The returned object must be released after use, by calling the [release] method.
  static MotionCallback? assignMotionCallback(MotionCallback? callback) {
    final _$callback = callback?.reference ?? jni$_.jNullReference;
    return _assignMotionCallback(
      _class.reference.pointer,
      _id_assignMotionCallback.pointer,
      _$callback.pointer,
    ).object<MotionCallback?>();
  }

  static final _id_clearListener = _class.staticMethodId(
    r'clearListener',
    r'()V',
  );

  static final _clearListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void clearListener()`
  static void clearListener() {
    _clearListener(_class.reference.pointer, _id_clearListener.pointer).check();
  }

  static final _id_dispatchKeyEvent = _class.staticMethodId(
    r'dispatchKeyEvent',
    r'(II)Z',
  );

  static final _dispatchKeyEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `static public boolean dispatchKeyEvent(int keyCode, int action)`
  static core$_.bool dispatchKeyEvent(core$_.int keyCode, core$_.int action) {
    return _dispatchKeyEvent(
      _class.reference.pointer,
      _id_dispatchKeyEvent.pointer,
      keyCode,
      action,
    ).boolean;
  }
}

final class $GamepadChannel$Type$ extends jni$_.JType<GamepadChannel> {
  @jni$_.internal
  const $GamepadChannel$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/marvinvogl/n_gamepad/GamepadChannel;';
}

/// from: `com.marvinvogl.n_gamepad.KeyCallback`
extension type KeyCallback._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/marvinvogl/n_gamepad/KeyCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<KeyCallback> type = $KeyCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $KeyCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onKeyEvent(II)V') {
        _$impls[$p]!.onKeyEvent(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(jni$_.JImplementer implementer, $KeyCallback $impl) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.marvinvogl.n_gamepad.KeyCallback',
      $p,
      _$invokePointer,
      [if ($impl.onKeyEvent$async) r'onKeyEvent(II)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory KeyCallback.implement($KeyCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<KeyCallback>();
  }
}

extension KeyCallback$$Methods on KeyCallback {
  static final _id_onKeyEvent = KeyCallback._class.instanceMethodId(
    r'onKeyEvent',
    r'(II)V',
  );

  static final _onKeyEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void onKeyEvent(int keyCode, int action)`
  void onKeyEvent(core$_.int keyCode, core$_.int action) {
    _onKeyEvent(
      reference.pointer,
      _id_onKeyEvent.pointer,
      keyCode,
      action,
    ).check();
  }
}

abstract base mixin class $KeyCallback {
  factory $KeyCallback({
    required void Function(core$_.int keyCode, core$_.int action) onKeyEvent,
    core$_.bool onKeyEvent$async,
  }) = _$KeyCallback;

  void onKeyEvent(core$_.int keyCode, core$_.int action);
  core$_.bool get onKeyEvent$async => false;
}

final class _$KeyCallback with $KeyCallback {
  _$KeyCallback({
    required this._onKeyEvent,
    this.onKeyEvent$async = false,
  });

  final void Function(core$_.int keyCode, core$_.int action) _onKeyEvent;
  final core$_.bool onKeyEvent$async;

  void onKeyEvent(core$_.int keyCode, core$_.int action) {
    return _onKeyEvent(keyCode, action);
  }
}

final class $KeyCallback$Type$ extends jni$_.JType<KeyCallback> {
  @jni$_.internal
  const $KeyCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/marvinvogl/n_gamepad/KeyCallback;';
}

/// from: `com.marvinvogl.n_gamepad.MotionCallback`
extension type MotionCallback._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/marvinvogl/n_gamepad/MotionCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MotionCallback> type = $MotionCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $MotionCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onMotionEvent(II)V') {
        _$impls[$p]!.onMotionEvent(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $MotionCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.marvinvogl.n_gamepad.MotionCallback',
      $p,
      _$invokePointer,
      [if ($impl.onMotionEvent$async) r'onMotionEvent(II)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory MotionCallback.implement($MotionCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<MotionCallback>();
  }
}

extension MotionCallback$$Methods on MotionCallback {
  static final _id_onMotionEvent = MotionCallback._class.instanceMethodId(
    r'onMotionEvent',
    r'(II)V',
  );

  static final _onMotionEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void onMotionEvent(int keyCode, int action)`
  void onMotionEvent(core$_.int keyCode, core$_.int action) {
    _onMotionEvent(
      reference.pointer,
      _id_onMotionEvent.pointer,
      keyCode,
      action,
    ).check();
  }
}

abstract base mixin class $MotionCallback {
  factory $MotionCallback({
    required void Function(core$_.int keyCode, core$_.int action) onMotionEvent,
    core$_.bool onMotionEvent$async,
  }) = _$MotionCallback;

  void onMotionEvent(core$_.int keyCode, core$_.int action);
  core$_.bool get onMotionEvent$async => false;
}

final class _$MotionCallback with $MotionCallback {
  _$MotionCallback({
    required this._onMotionEvent,
    this.onMotionEvent$async = false,
  });

  final void Function(core$_.int keyCode, core$_.int action) _onMotionEvent;
  final core$_.bool onMotionEvent$async;

  void onMotionEvent(core$_.int keyCode, core$_.int action) {
    return _onMotionEvent(keyCode, action);
  }
}

final class $MotionCallback$Type$ extends jni$_.JType<MotionCallback> {
  @jni$_.internal
  const $MotionCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/marvinvogl/n_gamepad/MotionCallback;';
}
